# Generated by Django 2.2.5 on 2019-09-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_desc', models.CharField(max_length=300)),
                ('task_deadline', models.DateTimeField(verbose_name='task deadline')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_desc', models.CharField(max_length=300)),
                ('action_datetime', models.DateTimeField(verbose_name='action datetime')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Task')),
            ],
        ),
    ]
